---
- hosts: localhost
  connection: local
  become_user: root
  become_method: sudo

  tasks:

  - include_tasks: enpass.yml
    vars:
      ansible_become: true
  - include_tasks: brave.yml
    vars:
      ansible_become: true
  - include_tasks: gnome-tweak-tool.yml
    vars:
      ansible_become: true
  - include_tasks: golang.yml
    vars:
      ansible_become: true
  - include_tasks: awscliv2.yml

  - name: Install classic snaps
    become: yes
    snap:
      name:
        - code
        - insomnia
      classic: yes
      channel: stable

  - name: Install apt packages
    become: yes
    apt:
      name:
        - vim
        - resolvconf
        - python3-pip
        - gufw

  - name: Install pip packages
    pip:
      name: pipenv
      extra_args: --user

  - name: set zsh as default shell
    become: yes
    user:
      name: brodie
      shell: /usr/bin/zsh

  - name: Set DNS servers
    become: yes
    blockinfile:
      path: /etc/resolvconf/resolv.conf.d/head
      insertafter: EOF
      block: |
        # Local codedns server
        nameserver 192.168.0.25
        nameserver 1.1.1.1
        nameserver 1.0.0.1
  
  - name: Reload resolvconf.service
    become: yes
    systemd:
      name: resolvconf.service
      state: restarted


  roles:
    - role: geerlingguy.docker
      become: yes
      vars:
        docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu eoan stable" # Setting to eoan until focal is supported
        docker_users:
          - brodie

    - role: gantsign.oh-my-zsh
      users:
        - username: brodie
          oh_my_zsh:
            theme: bureau
            plugins:
              - git
